# Generated by Django 6.1 on 2026-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(choices=[('liquor', 'Liquor'), ('grocery', 'Grocery'), ('both', 'Both')], default='both', max_length=20),
        ),
    ]
