# Generated by Django 6.1 on 2026-08-22 17:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_department'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 40.0 for 40% ABV', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.CharField(choices=[('liquor', 'Liquor'), ('grocery', 'Grocery'), ('both', 'Both / General')], default='liquor', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, default='', help_text='Country or Region of origin', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='MRP before discount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Comma-separated search tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, default='', help_text='e.g. 750ML, 1L, 5KG', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='SKU / Code'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['department'], name='products_pr_departm_ea8d15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'),
        ),
    ]
